####
## Service
####
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-app-test2
  #namespace: saas-generic
spec:
  selector:
    app: node-web-app-test2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

####
## Deployment
####
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-test2
  #namespace: saas-generic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web-app-test2
  template:
    metadata:
      labels:
        app: node-web-app-test2
    spec:
      containers:
        - name: node-web-app-test2
          image: iromain/node-web-app-test2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
