# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/node-web-app-test
          tags: latest,v1.0.1,registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Push image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - uses: extractions/netrc@80fc683
        with:
          machine: api.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}

      - run: sudo snap install --classic heroku

      - name: Release on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
